### ISSUE TITLE
Video Call Blank (Showing Black Screen)

### ISSUE THREAD

**Issue by arminbayu** [RodrigoBertotti/flutter_chat_app_with_nodejs#2]
Hello, when running your original code is running normal

I tried to use the video call feature with 2 Android emulators on the PC but only a black screen appeared on the recipient's screen (although chat works, and all features are normal except video calls)

No idea how to fix it.

SS
![Screenshot from 2023-10-31 14-27-30](https://github.com/RodrigoBertotti/flutter_chat_app_with_nodejs/assets/85722690/995a7b48-0eeb-455a-91de-78332ed9cfe0)

Flutter app
I/org.webrtc.Logging( 6775): CameraStatistics: Camera fps: 12.
I/org.webrtc.Logging( 6775): CameraStatistics: Camera fps: 12.
I/org.webrtc.Logging( 6775): EglRenderer: Duration: 4003 ms. Frames received: 45. Dropped: 0. Rendered: 45. Render fps: 11.2. Average render time: 677 us. Average swapBuffer time: 473 us.
I/org.webrtc.Logging( 6775): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 6775): EglRenderer: Duration: 4002 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 6775): CameraStatistics: Camera fps: 
I/org.webrtc.Logging( 6775): CameraStatistics: Camera fps: 12.
I/org.webrtc.Logging( 6775): EglRenderer: Duration: 4001 ms. Frames received: 46. Dropped: 0. Rendered: 46. Render fps: 11.5. Average render time: 672 us. Average swapBuffer time: 431 us.
I/org.webrtc.Logging( 6775): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

NPM server

info: onClientReceiveOutputWithSuccess being ignored for route askless-internal/call/listen-for-a-call (listen)
info: onClientReceiveOutputWithSuccess being ignored for route askless-internal/call/listen-for-a-call (listen)
info: onClientReceiveOutputWithSuccess being ignored for route askless-internal/call/ice-candidate-list (listen)

**Comment by RodrigoBertotti** [comment]
Hello, WebRTC is not supposed to work with Android Emulators, neither iOS simulators, please use a real device instead or try it with Flutter Web

**Comment by arminbayu** [comment]
Thanks you

**Comment by RodrigoBertotti** [comment]
welcome!
