### ISSUE TITLE
Video not stream using cellular data

### ISSUE THREAD

**Issue by josefrasetia** [RodrigoBertotti/flutter_chat_app_with_nodejs#3]
I tried using cellular data to make a video call, but the video was not displayed, only a black screen appeared

**Comment by RodrigoBertotti** [comment]
Hello, which device did you test it?

**Comment by josefrasetia** [comment]
i use android device for testing, in this case i use my server turn and success to stream video.
but when I build the release apk, the socket doesn't connect and runs perfectly in debug mode.  What is wrong?

**Comment by RodrigoBertotti** [comment]
does the text chat work well in production?

**Comment by josefrasetia** [comment]
The problem is nothing permission of internet in production. 
I add internet permission in manifest and my app is working. Thank you.

**Comment by RodrigoBertotti** [comment]
I'm glad it worked!

**Comment by RodrigoBertotti** [comment]
Also, thank you a lot for helping with the other GitHub issue!

**Comment by josefrasetia** [comment]
You're welcome.
i close this issue.
